name: Compila LaTeX e Pubblica PDF

on:
  push:
    # QUI diciamo a GitHub di avviare l'automazione SOLO quando fai push sul ramo Doc
    branches: ["Doc"] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice repository (dal ramo Doc)
        uses: actions/checkout@v4

      - name: Compila il file LaTeX in PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: analisi-requisiti-tecnici.tex # Controlla che il nome del tuo file tex sia corretto
          # args: -pdf -file-line-error -interaction=nonstopmode

      - name: Prepara i file per il sito web
        run: |
          mkdir -p public
          cp *.pdf public/
          if [ -f index.html ]; then cp index.html public/; fi

      - name: Carica l'artefatto di build
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pubblica su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4